---
apiVersion: v1
kind: Template
metadata:
  name: dashdotdb
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: dashdotdb
    name: dashdotdb
  spec:
    replicas: 3
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: dashdotdb
    template:
      metadata:
        labels:
          app: dashdotdb
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: dashdotdb
          env:
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${tokenSecret}
                  key: ACCESS_TOKEN
            - name: DATABASE_HOST
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.host
            - name: DATABASE_PORT
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.port
            - name: DATABASE_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.user
            - name: DATABASE_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: ${databaseSecret}
                   key: db.password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: ${databaseSecret}
                  key: db.name
          ports:
          - name: dashdotdb
            containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: dashdotdb
    labels:
      app: dashdotdb
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
        name: dashdotdb
    selector:
      app: dashdotdb
parameters:
- name: IMAGE
  value: quay.io/app-sre/dashdotdb
- name: IMAGE_TAG
  value: latest
- name: databaseSecret
  value: dashdotdb-rds
- name: tokenSecret
  value: access-token
